### ISSUE TITLE
Symfony FileLocatorFileNotFoundException

### ISSUE THREAD

**Issue by filipagh** [composer-unused/composer-unused#305]
## Describe the bug

after resolve of this [issue](https://github.com/composer-unused/composer-unused/issues/284) test on `dev-main` result to this error

```
 vendor/bin/composer-unused 


PHP Fatal error:  Uncaught Symfony\Component\Config\Exception\FileLocatorFileNotFoundException: The file "/srv/http/LiveAgent/LiveAgent/server/vendor/icanhazstring/composer-unused/config/../vendor/composer-unused/symbol-parser/src" does not exist. in /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/config/FileLocator.php:44
Stack trace:
#0 /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/config/Loader/FileLoader.php(118): Symfony\Component\Config\FileLocator->locate()
#1 /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/dependency-injection/Loader/FileLoader.php(194): Symfony\Component\Config\Loader\FileLoader->glob()
#2 /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/dependency-injection/Loader/FileLoader.php(105): Symfony\Component\DependencyInjection\Loader\FileLoader->findClasses()
#3 /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/dependency-injection/Loader/Configurator/PrototypeConfigurator.php(69): Symfony\Component\DependencyInjection\Loader\FileLoader->registerClasses()
#4 /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/dependency-injection/Loader/Configurator/AbstractServiceConfigurator.php(69): Symfony\Component\DependencyInjection\Loader\Configurator\PrototypeConfigurator->__destruct()
#5 /srv/http/LiveAgent/LiveAgent/server/vendor/icanhazstring/composer-unused/config/services.php(36): Symfony\Component\DependencyInjection\Loader\Configurator\AbstractServiceConfigurator->load()
#6 /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(151): Symfony\Component\DependencyInjection\Loader\ProtectedPhpFileLoader::{closure}()
#7 /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/dependency-injection/Loader/PhpFileLoader.php(67): Symfony\Component\DependencyInjection\Loader\PhpFileLoader->executeCallback()
#8 /srv/http/LiveAgent/LiveAgent/server/vendor/icanhazstring/composer-unused/config/container.php(12): Symfony\Component\DependencyInjection\Loader\PhpFileLoader->load()
#9 /srv/http/LiveAgent/LiveAgent/server/vendor/icanhazstring/composer-unused/config/container.php(21): {closure}()
#10 /srv/http/LiveAgent/LiveAgent/server/vendor/icanhazstring/composer-unused/bin/composer-unused(39): require('/srv/http/LiveA...')
#11 /srv/http/LiveAgent/LiveAgent/server/vendor/icanhazstring/composer-unused/bin/composer-unused(46): {closure}()
#12 {main}
  thrown in /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/config/FileLocator.php on line 44

```

**Comment by icanhazstring** [comment]
Can you give me some more information?

- php version
- composer.json (content)

**Comment by filipagh** [comment]
PHP 8.0.14 

<details>
  <summary>composer.json</summary>
  

  ```
{
    "config": {
         "platform": {
             "php": "7.4"
         }
     },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://bitbucket.org/archon810/smartdomdocument.git"
        },
        {
            "type": "vcs",
            "url": "https://github.com/QualityUnit/monolog-cascade.git"
        }
    ],
    "require": {
        "php": "^7.2|^8",
        "ext-bcmath": "^7.2|^8",
        "ext-gd": "^7.2|^8",
        "ext-exif": "^7.2|^8",
        "ext-iconv": "^7.2|^8",
        "ext-mbstring": "^7.2|^8",
        "ext-fileinfo": "*",
        "ext-xml": "^7.2|^8",
        "ext-intl": "*",
        "ext-curl": "^7.2|^8",
        "ext-pdo_mysql": "^7.2|^8",
        "ext-json": "*",
        "ext-pdo": "^7.2|^8.0",
        "ext-sockets": "^7.2|^8",
        "ext-ctype": "^7.2|^8",
        "ext-filter": "^7.2|^8",
        "ext-redis": "*",
        "guzzlehttp/guzzle": "^6.2",
        "aws/aws-sdk-php": "^3.24.2",
        "google/apiclient": "~2.12.1",
        "elasticsearch/elasticsearch": "~7.0",
        "zendesk/zendesk_api_client_php": "^2.1",
        "qualityunit/resqu-client": "^5",
        "bandwidth-throttle/token-bucket": "^2.0",
        "qualityunit/statsd-client": "^1.0",
        "phpseclib/phpseclib": "~3.0",
        "archon810/smartdomdocument": "^0.4.2",
        "fabiang/sasl": "^1.0",
        "pear/console_getopt": "^1.4",
        "geoip2/geoip2": "^2.9",
        "qualityunit/tnef-decoder": "^1.0",
        "jolicode/slack-php-api": "^4.0",
        "helpscout/api": "^3.3",
        "ezyang/htmlpurifier": "^4.12",
        "facebook/graph-sdk": "^5.7",
        "slim/slim": "^4.3",
        "pear/mail_mime": "^1.10",
        "braintree/braintree_php": "^6.1",
        "jhut89/mailchimp3php": "^3.1",
        "bjeavons/zxcvbn-php": "^1.0",
        "knplabs/github-api":"^3.0",
        "icawebdesign/hibp-php": "^4.3.0",
        "prestashop/prestashop-webservice-lib": "dev-master",
        "middlewares/trailing-slash": "^2.0",
        "nyholm/psr7": "^1.3",
        "ralouphie/mimey": "^2.1",
        "php-http/guzzle6-adapter": "^2.0",
        "getresponse/sdk-php": "^2.0",
        "pipedrive/pipedrive": "^4.0",
        "smarty/smarty": "^4.0",
        "symfony/filesystem": "^5.2",
        "symfony/yaml": "^5.2",
        "league/container": "^4.2",
        "themattharris/tmhoauth": "^0.8.4",
        "psr/event-dispatcher": "^1.0",
        "symfony/event-dispatcher": "^5.3",
        "enshrined/svg-sanitize": "^0.14.0",
        "zbateson/mail-mime-parser": "^2.0",
        "templateria/spamassassin": "dev-master",
        "myclabs/php-enum": "^1.7",
        "envms/fluentpdo": "2.2.2",
        "monolog/monolog": "^2.2",
        "qualityunit/monolog-cascade": "^0.6.1",
        "ramsey/uuid": "^4.1",
        "mlocati/spf-lib": "^3.1",
        "amphp/http-client": "^4.5",
        "phpmailer/phpmailer": "^6.2",
        "nyholm/psr7-server": "^1.0",
        "defuse/php-encryption": "^2.3",
        "symfony/process": "^5.3",
        "symfony/mailer": "^5.3",
        "nesbot/carbon": "^2.54",
        "psr/log": "^1.1",
        "psr/http-message": "^1.0",
        "psr/http-server-handler": "^1.0",
        "psr/container": "^1.0",
        "symfony/mime": "5.4.0",
        "zbateson/mb-wrapper": "^1.1",
        "firebase/php-jwt": "^5.5",
        "symfony/event-dispatcher-contracts": "^2.4",
        "symfony/polyfill-php80": "^1.23",
        "chillerlan/php-qrcode": "^4.3"

    },
    "suggest": {
        "ext-pdo": "Recommended",
        "ext-pdo_mysql": "Recommended"
    },
    "autoload": {
        "psr-4": {
            "Qu\\La\\": "include/Qu/La",
            "Qu\\Lib\\": "include/Qu/Lib"
        },
        "files": [
            "include/Gpf.class.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Qu\\La\\": "tests/Qu/La",
            "Qu\\Lib\\": "tests/Qu/Lib"
        }
    },
    "require-dev": {
        "phpunit/phpunit": "^9.1",
        "overtrue/phplint": "^3.0",
        "brianium/paratest": "^6.1",
        "kostaspt/php-ns-fixer": "master@dev",
        "phpstan/phpstan": "^1.0.0",
        "icanhazstring/composer-unused": "dev-main"
    }
}

  ```
  
</details>

**Comment by icanhazstring** [comment]
Thanks will try and check what is going on 👍

**Comment by icanhazstring** [comment]
Ok found the issue. Fix incoming :)

**Comment by icanhazstring** [comment]
Fixed with latest `dev-main`
