### ISSUE TITLE
Config name accessed but not inicialized

### ISSUE THREAD

**Issue by filipagh** [composer-unused/composer-unused#307]
## Describe the bug 
`dev-main`
after this [issue](https://github.com/composer-unused/composer-unused/issues/305) 
```
PHP Fatal error:  Uncaught Error: Typed property ComposerUnused\ComposerUnused\Composer\Config::$name must not be accessed before initialization in /srv/http/LiveAgent/LiveAgent/server/vendor/icanhazstring/composer-unused/src/Composer/Config.php:25
Stack trace:
#0 /srv/http/LiveAgent/LiveAgent/server/vendor/icanhazstring/composer-unused/src/Composer/PackageFactory.php(16): ComposerUnused\ComposerUnused\Composer\Config->getName()
#1 /srv/http/LiveAgent/LiveAgent/server/vendor/icanhazstring/composer-unused/src/Console/Command/UnusedCommand.php(138): ComposerUnused\ComposerUnused\Composer\PackageFactory->fromConfig()
#2 /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/console/Command/Command.php(298): ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute()
#3 /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#4 /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#5 /srv/http/LiveAgent/LiveAgent/server/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#6 /srv/http/LiveAgent/LiveAgent/server/vendor/icanhazstring/composer-unused/bin/composer-unused(45): Symfony\Component\Console\Application->run()
#7 /srv/http/LiveAgent/LiveAgent/server/vendor/icanhazstring/composer-unused/bin/composer-unused(46): {closure}()
#8 {main}
  thrown in /srv/http/LiveAgent/LiveAgent/server/vendor/icanhazstring/composer-unused/src/Composer/Config.php on line 25

```

**Comment by icanhazstring** [comment]
Duplicate to #300.
You `composer.json` config is not valid.
