### ISSUE TITLE
Config::$name must not be accessed before initialization

### ISSUE THREAD

**Issue by beeyev** [composer-unused/composer-unused#311]
When I run the tool with this command
`composer-unused --no-progress --excludeDir=bin --excludeDir=config`
I receive this error
```
PHP Fatal error:  Uncaught Error: Typed property ComposerUnused\ComposerUnused\Composer\Config::$name must not be accessed before initialization in phar:///usr/local/bin/composer-unused/src/Composer/Config.php:23
Stack trace:
#0 phar:///usr/local/bin/composer-unused/src/Composer/Package.php(22): ComposerUnused\ComposerUnused\Composer\Config->getName()
#1 phar:///usr/local/bin/composer-unused/src/Console/Command/UnusedCommand.php([127](https://gitlab.com/insigne/andstone/backend/as-backend/-/jobs/2072166444#L127)): ComposerUnused\ComposerUnused\Composer\Package::fromConfig()
#2 phar:///usr/local/bin/composer-unused/vendor/symfony/console/Command/Command.php(298): ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute()
#3 phar:///usr/local/bin/composer-unused/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command->run()
#4 phar:///usr/local/bin/composer-unused/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#5 phar:///usr/local/bin/composer-unused/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#6 phar:///usr/local/bin/composer-unused/bin/composer-unused(43): Symfony\Component\Console\Application->run()
#7 phar:///usr/local/bin/composer-unused/bin/composer-unused(44): {closure}()
#8 /usr/local/bin/composer-unused(14): require('...')
#9 {main}
  thrown in phar:///usr/local/bin/composer-unused/src/Composer/Config.php on line 23
```
It looks like this issue
https://bugs.php.net/bug.php?id=79620

PHP 8.1, composer-unused is the latest

**Comment by icanhazstring** [comment]
Duplicate #307
