### ISSUE TITLE
`InvalidDependency` cannot be mark as used. 

### ISSUE THREAD

**Issue by scyzoryck** [composer-unused/composer-unused#313]
First of all - thanks for the tool - it is really useful and helpful to keep composer.json without not needed dependencies :) 

## Describe the bug

It looks like script execution will finish with fatal error when we have invalid dependency, but another (valid one) depends on it. Then  script is trying to mark it as used, but there is no such method in `InvalidDependency` class.

## Additional information
Stack trace:
```
Fatal error: Uncaught Error: Call to undefined method ComposerUnused\ComposerUnused\Dependency\InvalidDependency::markUsed() in phar:///app/composer-unused.phar/src/Console/Command/UnusedCommand.php:180
Stack trace:
#0 phar:///app/composer-unused.phar/vendor/symfony/console/Command/Command.php(298): ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar:///app/composer-unused.phar/vendor/symfony/console/Application.php(1015): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///app/composer-unused.phar/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(ComposerUnused\ComposerUnused\Console\Command\UnusedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///app/composer-unused.phar/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///app/composer-unused.phar/bin/composer-unused(43): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#5 phar:///app/composer-unused.phar/bin/composer-unused(44): {closure}(Array)
#6 /app/composer-unused.phar(14): require('phar:///app/com...')
#7 {main}
  thrown in phar:///app/composer-unused.phar/src/Console/Command/UnusedCommand.php on line 180
```

## Proposed solution
After adding `markUsed` method to `InvalidDependency` class (and interface) it parse all dependencies correctly (marking invalid one as used).  If you are fine with such solution I can prepare PR with a fix to it. Currently I have no public reproduction for it - I can create one if needed.

**Comment by icanhazstring** [comment]
I. Thanks for the report.
The `InvalidDependency` class is no longer present as of `dev-main`

I will release a new version so.
In the meantime you can try if you problem still persists with when using the dev branch. 😉

**Comment by scyzoryck** [comment]
Hi! Thank you for quick answer :) 

I've tried to test with main version, but it looks like it dropped support for packages installed via composer 1.x - due to missing `vendor/composer/installed.php` file - that has been added in composer 2.0. I will try to update repo to composer 2.x first and rerun the tests. 

Stack trace: 
```
Warning: require(/app/vendor/composer/installed.php): Failed to open stream: No such file or directory in /app/unused/src/Composer/LocalRepositoryFactory.php on line 28

Fatal error: Uncaught Error: Failed opening required '/app/vendor/composer/installed.php' (include_path='.:/usr/local/lib/php') in /app/unused/src/Composer/LocalRepositoryFactory.php:28
Stack trace:
#0 /app/unused/src/Console/Command/UnusedCommand.php(139): ComposerUnused\ComposerUnused\Composer\LocalRepositoryFactory->create(Object(ComposerUnused\ComposerUnused\Composer\Config))
#1 /app/unused/vendor/symfony/console/Command/Command.php(291): ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /app/unused/vendor/symfony/console/Application.php(989): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /app/unused/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand(Object(ComposerUnused\ComposerUnused\Console\Command\UnusedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /app/unused/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /app/unused/bin/composer-unused(45): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#6 /app/unused/bin/composer-unused(46): {closure}(Array)
#7 {main}
  thrown in /app/unused/src/Composer/LocalRepositoryFactory.php on line 28
```

**Comment by icanhazstring** [comment]
As composer 1.1 is not maintained anymore. Yes. composer-unused requires composer 2 :)

**Comment by scyzoryck** [comment]
I've tested with newest `main` branch - the initial issue is resolved, so I think we can close the issue. :) 

I've found some weird issue with composer (?) - it looks like `install_paths` are missing in `installed.php`, but paths are saved in  `installed.json`. I need a deeper look at it - as it might be connected with fact that the dependencies was initially installed via composer1.

**Comment by icanhazstring** [comment]
@scyzoryck thanks for checking. I will close this issue then.
If there is another one happening, don't hesitate to create another issue :)
