### ISSUE TITLE
Phar not autoloading classes properly on 0.8.2

### ISSUE THREAD

**Issue by LucaGallinari** [composer-unused/composer-unused#340]
## Describe the bug
I am not able to run the phar file on 0.8.2 but it works with 0.8.1.
It gives this error:

```
PHP Fatal error:  Uncaught Error: Class 'ComposerUnused\ComposerUnused\Configuration\NamedFilter' not found in /Users/me/workspace/my-project/composer-unused.php:10
Stack trace:
#0 phar:///usr/local/bin/composer-unused.phar/src/Console/Command/UnusedCommand.php(132): __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Command\UnusedCommand::{closure}(Object(__ComposerUnused__\ComposerUnused\ComposerUnused\Configuration\Configuration))
#1 phar:///usr/local/bin/composer-unused.phar/src/Console/Command/UnusedCommand.php(70): __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->loadConfiguration('/Users/luke/wor...')
#2 phar:///usr/local/bin/composer-unused.phar/vendor/symfony/console/Command/Command.php(259): __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute(Object(__ComposerUnused__\Symfony\Component\Console\Input\ArgvInput), Object(__ComposerUnused__\Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/composer-unused.phar/vendor/sym in /Users/me/workspace/my-project/composer-unused.php on line 1
```

So, it's probably an autoloading problem.

## Additional information
I am running php 7.4
I have the phar file in the /usr/local/bin folder
I have a custom composer-unused.php file with the following content:
```
<?php

declare(strict_types=1);

use ComposerUnused\ComposerUnused\Configuration\Configuration;
use ComposerUnused\ComposerUnused\Configuration\NamedFilter;

return static function (Configuration $config): Configuration {
    return $config
        ->addNamedFilter(NamedFilter::fromString('cweagans/composer-patches'))
        ->addNamedFilter(NamedFilter::fromString('symfony/flex'))
        ->setAdditionalFilesFor(
            'my-vendor/my-project',
            [__DIR__ . '/config/bundles.php', __DIR__ . '/config/bootstrap.php']
        )
    ;
};
```

This is probably due to https://github.com/composer-unused/composer-unused/pull/339 ?

**Comment by icanhazstring** [comment]
Thanks for the report. Let me check

**Comment by icanhazstring** [comment]
I have re-released the phar. Should be fixed now :)

**Comment by LucaGallinari** [comment]
Ok now i works! Thanks
