### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Typed property

### ISSUE THREAD

**Issue by lazka** [composer-unused/composer-unused#345]
## Describe the bug

I upgraded from 0.7.x to the latest version, and I now get this:

```php
PHP Fatal error:  Uncaught Error: Typed property __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Config::$name must not be accessed before initialization in phar:///home/lazka/composer-unused.phar/src/Composer/Config.php:23
Stack trace:
#0 phar:///home/lazka/composer-unused.phar/src/Composer/PackageFactory.php(12): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Config->getName()
#1 phar:///home/lazka/composer-unused.phar/src/Console/Command/UnusedCommand.php(67): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory->fromConfig()
#2 phar:///home/lazka/composer-unused.phar/vendor/symfony/console/Command/Command.php(259): __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute()
#3 phar:///home/lazka/composer-unused.phar/vendor/symfony/console/Application.php(856): __ComposerUnused__\Symfony\Component\Console\Command\Command->run()
#4 phar:///home/lazka/composer-unused.phar/vendor/symfony/console/Application.php(259): __ComposerUnused__\Symfony\Component\Console\Application->doRunCommand()
#5 phar:///home/lazka/composer-unused.phar/vendor/symfony/console/Application.php(157): __ComposerUnused__\Symfony\Component\Console\Application->doRun()
#6 phar:///home/lazka/composer-unused.phar/bin/composer-unused(26): __ComposerUnused__\Symfony\Component\Console\Application->run()
#7 phar:///home/lazka/composer-unused.phar/bin/composer-unused(27): __ComposerUnused__\{closure}()
#8 /home/lazka/composer-unused.phar(14): require('...')
#9 {main}
  thrown in phar:///home/lazka/composer-unused.phar/src/Composer/Config.php on line 23
```

## Additional information

Using PHP 8.1.3 on Ubuntu

I've downgraded to 0.7.11 again, which works fine.

**Comment by icanhazstring** [comment]
Hi. Adding a `name` property to your `composer.json` should fix this.

**Comment by lazka** [comment]
Ah, thanks, that's it :)

Maybe it should not fail if it is missing?

**Comment by icanhazstring** [comment]
I will improve the behavior in the future. Yes :)
