### ISSUE TITLE
composer-unused.phar - PHP Fatal error:  Uncaught Error: Typed property

### ISSUE THREAD

**Issue by tomasnorre** [composer-unused/composer-unused#350]
## Describe the bug

I have just downloaded the latest composer-unused.phar file 

```shell
➜ sha256sum composer-unused.phar 
796b27d142e07179857458fe66840e09afd14be4ee98ab37623d152d941d89c9  composer-unused.phar
```

When I run the command, I get an error instantly. 

```shell 
$ php composer-unused.phar  

PHP Fatal error:  Uncaught Error: Typed property __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Config::$name must not be accessed before initialization in phar:///path/to/project/composer-unused.phar/src/Composer/Config.php:23
Stack trace:
#0 phar:///path/to/project/composer-unused.phar/src/Composer/PackageFactory.php(12): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Config->getName()
#1 phar:///path/to/project/composer-unused.phar/src/Console/Command/UnusedCommand.php(67): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory->fromConfig()
#2 phar:///path/to/project/composer-unused.phar/vendor/symfony/console/Command/Command.php(259): __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute()
#3 phar:///path/to/project/composer-unused.phar/vendor in phar:///path/to/project/composer-unused.phar/src/Composer/Config.php on line 23
```

## Additional information

I'm on PHP 7.4.28 so should be a compatible PHP version according to composer.json of the `main` branch. 

Let me know if you need any additional information, or help testing etc.

**Comment by tomasnorre** [comment]
This is the output with PHP 8.0.17 

```shell 
$ php composer-unused.phar
PHP Fatal error:  Uncaught Error: Typed property __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Config::$name must not be accessed before initialization in phar:///path/to/project/composer-unused.phar/src/Composer/Config.php:23
Stack trace:
#0 phar:///path/to/project/composer-unused.phar/src/Composer/PackageFactory.php(12): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Config->getName()
#1 phar:///path/to/project/composer-unused.phar/src/Console/Command/UnusedCommand.php(67): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory->fromConfig()
#2 phar:///path/to/project/composer-unused.phar/vendor/symfony/console/Command/Command.php(259): __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute()
#3 phar:///path/to/project/composer-unused.phar/vendor/symfony/console/Application.php(856): __ComposerUnused__\Symfony\Component\Console\Command\Command->run()
#4 phar:///path/to/project/composer-unused.phar/vendor/symfony/console/Application.php(259): __ComposerUnused__\Symfony\Component\Console\Application->doRunCommand()
#5 phar:///path/to/project/composer-unused.phar/vendor/symfony/console/Application.php(157): __ComposerUnused__\Symfony\Component\Console\Application->doRun()
#6 phar:///path/to/project/composer-unused.phar/bin/composer-unused(26): __ComposerUnused__\Symfony\Component\Console\Application->run()
#7 phar:///path/to/project/composer-unused.phar/bin/composer-unused(27): __ComposerUnused__\{closure}()
#8 /path/to/project/composer-unused.phar(14): require('...')
#9 {main}
  thrown in phar:///path/to/project/composer-unused.phar/src/Composer/Config.php on line 23
 ```

**Comment by icanhazstring** [comment]
Hi @tomasnorre. Probably your `composer.json` is missing the `name` property.

Try adding it for now. I will try and improve the error or even support to make it optional. But right now it is a needed value.

**Comment by tomasnorre** [comment]
Doh.. My bad, didn't think of checking with `composer validate`, as everything else worked like expected. 

Sorry. But thanks for your help, it works now.

**Comment by icanhazstring** [comment]
Yeah, for `composer` the `name` is only mandatory for libraries which a published using packagist
