### ISSUE TITLE
Requires SF property access

### ISSUE THREAD

**Issue by simPod** [composer-unused/composer-unused#430]
## Describe the bug

`vendor/bin/composer-unused --no-progress`

```
PHP Fatal error:  Uncaught Error: Class "Symfony\Component\PropertyAccess\PropertyAccess" not found in /path/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php:328
Stack trace:
#0 /path/vendor/symfony/serializer/Serializer.php(227): Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer->denormalize(Array, 'ComposerUnused\\...', 'json', Array)
#1 /path/vendor/symfony/serializer/Serializer.php(145): Symfony\Component\Serializer\Serializer->denormalize(Array, 'ComposerUnused\\...', 'json', Array)
#2 /path/vendor/icanhazstring/composer-unused/src/Composer/ConfigFactory.php(36): Symfony\Component\Serializer\Serializer->deserialize(Array, 'ComposerUnused\\...', 'json')
#3 /path/vendor/icanhazstring/composer-unused/src/Console/Command/UnusedCommand.php(136): ComposerUnused\ComposerUnused\Composer\ConfigFactory->fromPath('/Users/user/Wor...')
#4 /path/vendor/symfony/console/Command/Command.php(312): ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /path/vendor/symfony/console/Application.php(1020): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /path/vendor/symfony/console/Application.php(312): Symfony\Component\Console\Application->doRunCommand(Object(ComposerUnused\ComposerUnused\Console\Command\UnusedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /path/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /path/vendor/icanhazstring/composer-unused/bin/composer-unused(45): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#9 /path/vendor/icanhazstring/composer-unused/bin/composer-unused(46): {closure}(Array)
#10 /path/vendor/bin/composer-unused(120): include('/Users/user/Wor...')
#11 {main}
  thrown in /path/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php on line 328
```

I think we have a missing requirement here?

## Additional information
php 8.1.13

**Comment by simPod** [comment]
Hm, I see it's required 🤔

**Comment by simPod** [comment]
But not in my lockfile:

```
        {
            "name": "icanhazstring/composer-unused",
            "version": "0.8.4",
            "source": {
                "type": "git",
                "url": "https://github.com/composer-unused/composer-unused.git",
                "reference": "af9085d2058333d26559b334c536c40fb04e28d3"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/composer-unused/composer-unused/zipball/af9085d2058333d26559b334c536c40fb04e28d3",
                "reference": "af9085d2058333d26559b334c536c40fb04e28d3",
                "shasum": ""
            },
            "require": {
                "composer-unused/contracts": "^0.2",
                "composer-unused/symbol-parser": "^0.1.10",
                "ext-json": "*",
                "nikic/php-parser": "^4.15",
                "ondram/ci-detector": "^4.1",
                "php": "^7.4 || ^8.0",
                "phpstan/phpdoc-parser": "^1.10",
                "psr/container": "^1.0 || ^2.0",
                "psr/log": "^1.1 || ^2 || ^3",
                "symfony/config": "^4.4 || ^5.4 || ^6.0",
                "symfony/console": "^4.4 || ^5.4 || ^6.0",
                "symfony/dependency-injection": "^4.4.8 || ^5.4 || ^6.0",
                "symfony/serializer": "^4.4 || ^5.4 || ^6.0",
                "webmozart/assert": "^1.10",
                "webmozart/glob": "^4.4"
            },
            "require-dev": {
                "dg/bypass-finals": "^1.4",
                "ext-ds": "*",
                "ext-zend-opcache": "*",
                "jangregor/phpstan-prophecy": "^0.8.1",
                "phpspec/prophecy-phpunit": "^2.0.1",
                "phpstan/phpstan": "^0.12.99",
                "phpunit/phpunit": "^9.5.25",
                "roave/security-advisories": "dev-master",
                "squizlabs/php_codesniffer": "^3.7"
            },
            "bin": [
                "bin/composer-unused"
            ],
            "type": "library",
            "autoload": {
                "psr-4": {
                    "ComposerUnused\\ComposerUnused\\": "src"
                }
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "MIT"
            ],
            "authors": [
                {
                    "name": "Andreas Frömer",
                    "email": "composer-unused@icanhazstring.com"
                }
            ],
            "description": "Show unused packages by scanning your code",
            "homepage": "https://github.com/composer-unused/composer-unused",
            "keywords": [
                "composer",
                "php-parser",
                "unused"
            ],
            "support": {
                "issues": "https://github.com/composer-unused/composer-unused/issues",
                "source": "https://github.com/composer-unused/composer-unused"
            },
            "funding": [
                {
                    "url": "https://github.com/sponsors/icanhazstring",
                    "type": "github"
                },
                {
                    "url": "https://paypal.me/icanhazstring",
                    "type": "other"
                }
            ],
            "time": "2022-10-13T05:46:37+00:00"
        },
```

**Comment by simPod** [comment]
Ok lol https://github.com/composer-unused/composer-unused/pull/428

**Comment by icanhazstring** [comment]
Release with it coming soon :)

**Comment by icanhazstring** [comment]
And done. 0.8.5
