### ISSUE TITLE
Plugin - Class "__ComposerUnused__\Symfony\Component\DependencyInjection\ContainerBuilder" not found

### ISSUE THREAD

**Issue by grizzlylab** [composer-unused/composer-unused#451]
## Describe the bug
Error when executing `composer require composer-unused/composer-unused-plugin`

## Additional information
- COMPOSER 2.5.4
- PHP 8.1
![Screenshot from 2023-03-01 15-22-26](https://user-images.githubusercontent.com/2612537/222167720-cff81107-5e0d-4751-b638-a12ab627619e.png)

## Exception trace 
```Exception trace:
  at phar:///srv/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php:10
 ComposerUnused\ComposerUnusedPlugin\UnusedPlugin::__ComposerUnused__\{closure}() at phar:///srv/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php:18
 require() at /srv/vendor/composer-unused/composer-unused-plugin/src/UnusedPlugin.php:36
 ComposerUnused\ComposerUnusedPlugin\UnusedPlugin->activate() at phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:388
 Composer\Plugin\PluginManager->addPlugin() at phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php:292
 Composer\Plugin\PluginManager->registerPackage() at phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php:85
 Composer\Installer\PluginInstaller->Composer\Installer\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/FulfilledPromise.php:28
 React\Promise\FulfilledPromise->then() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:134
 React\Promise\Promise::React\Promise\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:168
 React\Promise\Promise->settle() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:231
 React\Promise\Promise::React\Promise\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/FulfilledPromise.php:42
 React\Promise\FulfilledPromise->done() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:135
 React\Promise\Promise::React\Promise\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:168
 React\Promise\Promise->settle() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:231
 React\Promise\Promise::React\Promise\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/FulfilledPromise.php:42
 React\Promise\FulfilledPromise->done() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:66
 React\Promise\Promise::React\Promise\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:168
 React\Promise\Promise->settle() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:231
 React\Promise\Promise::React\Promise\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/FulfilledPromise.php:42
 React\Promise\FulfilledPromise->done() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:135
 React\Promise\Promise::React\Promise\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:168
 React\Promise\Promise->settle() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:231
 React\Promise\Promise::React\Promise\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/FulfilledPromise.php:42
 React\Promise\FulfilledPromise->done() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:135
 React\Promise\Promise::React\Promise\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:168
 React\Promise\Promise->settle() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:231
 React\Promise\Promise::React\Promise\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/FulfilledPromise.php:42
 React\Promise\FulfilledPromise->done() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:135
 React\Promise\Promise::React\Promise\{closure}() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:168
 React\Promise\Promise->settle() at phar:///usr/local/bin/composer/vendor/react/promise/src/Promise.php:231
 React\Promise\Promise::React\Promise\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php:327
 Composer\Util\ProcessExecutor->countActiveJobs() at phar:///usr/local/bin/composer/src/Composer/Util/Loop.php:91
 Composer\Util\Loop->wait() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:430
 Composer\Installer\InstallationManager->waitOnPromises() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:405
 Composer\Installer\InstallationManager->executeBatch() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:319
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:218
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/bin/composer/src/Composer/Installer.php:797
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:622
 Composer\Installer->doUpdate() at phar:///usr/local/bin/composer/src/Composer/Installer.php:287
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:490
 Composer\Command\RequireCommand->doUpdate() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:339
 Composer\Command\RequireCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:298
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:1040
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:301
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:377
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:171
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:141
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:88
 require() at /usr/local/bin/composer:29
```

**Comment by icanhazstring** [comment]
Hi. Thanks for reporting.
Might be due to broken phar build of composer-unused.

**Comment by Hanmac** [comment]
Similar Stacktrace

```
  - Installing composer-unused/composer-unused-plugin (0.8.10): Extracting archive
PHP Fatal error:  Uncaught Error: Class "__ComposerUnused__\Symfony\Component\DependencyInjection\ContainerBuilder" not found in phar:///var/www/html/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php:10
Stack trace:
#0 phar:///var/www/html/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php(18): ComposerUnused\ComposerUnusedPlugin\UnusedPlugin::__ComposerUnused__\{closure}()
#1 /var/www/html/vendor/composer-unused/composer-unused-plugin/src/UnusedPlugin.php(36): require('phar:///var/www...')
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(335): ComposerUnused\ComposerUnusedPlugin\UnusedPlugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(231): Composer\Plugin\PluginManager->addPlugin(Object(ComposerUnused\ComposerUnusedPlugin\UnusedPlugin), false, Object(Composer\Package\CompletePackage))
#4 phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php(79): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#5 [internal function]: Composer\Installer\PluginInstaller->Composer\Installer\{closure}(NULL)
#6 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Object(Closure), NULL)
#7 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(74): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#8 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#9 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#10 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#11 [internal function]: React\Promise\Deferred->resolve(NULL)
#12 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, NULL)
#13 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#14 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#15 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#16 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#17 [internal function]: React\Promise\Deferred->resolve(NULL)
#18 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, NULL)
#19 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(74): React\Promise\FulfilledPromise->then(Array, Array)
#20 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#21 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#22 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#23 [internal function]: React\Promise\Deferred->resolve(NULL)
#24 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, NULL)
#25 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#26 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#27 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#28 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#29 [internal function]: React\Promise\Deferred->resolve(true)
#30 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, true)
#31 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#32 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#33 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#34 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#35 [internal function]: React\Promise\Deferred->resolve(Object(Symfony\Component\Process\Process))
#36 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, Object(Symfony\Component\Process\Process))
#37 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#38 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#39 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#40 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#41 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Promise.php(42): React\Promise\Deferred->resolve(Object(Symfony\Component\Process\Process))
#42 [internal function]: React\Promise\Promise->React\Promise\{closure}(Object(Symfony\Component\Process\Process))
#43 phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php(316): call_user_func(Object(Closure), Object(Symfony\Component\Process\Process))
#44 phar:///usr/local/bin/composer/src/Composer/Util/Loop.php(92): Composer\Util\ProcessExecutor->countActiveJobs()
#45 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(462): Composer\Util\Loop->wait(Array, NULL)
#46 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(440): Composer\Installer\InstallationManager->waitOnPromises(Array)
#47 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(367): Composer\Installer\InstallationManager->executeBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array)
#48 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(266): Composer\Installer\InstallationManager->downloadAndExecuteBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array)
#49 phar:///usr/local/bin/composer/src/Composer/Installer.php(706): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Array, true, true)
#50 phar:///usr/local/bin/composer/src/Composer/Installer.php(543): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), true)
#51 phar:///usr/local/bin/composer/src/Composer/Installer.php(247): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#52 phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php(241): Composer\Installer->run()
#53 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#54 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#55 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#56 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(314): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#57 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#58 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(125): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#59 phar:///usr/local/bin/composer/bin/composer(67): Composer\Console\Application->run()
#60 /usr/local/bin/composer(24): require('phar:///usr/loc...')
#61 {main}
  thrown in phar:///var/www/html/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php on line 10

Fatal error: Uncaught Error: Class "__ComposerUnused__\Symfony\Component\DependencyInjection\ContainerBuilder" not found in phar:///var/www/html/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php:10
Stack trace:
#0 phar:///var/www/html/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php(18): ComposerUnused\ComposerUnusedPlugin\UnusedPlugin::__ComposerUnused__\{closure}()
#1 /var/www/html/vendor/composer-unused/composer-unused-plugin/src/UnusedPlugin.php(36): require('phar:///var/www...')
#2 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(335): ComposerUnused\ComposerUnusedPlugin\UnusedPlugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#3 phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php(231): Composer\Plugin\PluginManager->addPlugin(Object(ComposerUnused\ComposerUnusedPlugin\UnusedPlugin), false, Object(Composer\Package\CompletePackage))
#4 phar:///usr/local/bin/composer/src/Composer/Installer/PluginInstaller.php(79): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage), true)
#5 [internal function]: Composer\Installer\PluginInstaller->Composer\Installer\{closure}(NULL)
#6 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Object(Closure), NULL)
#7 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(74): React\Promise\FulfilledPromise->then(Object(Closure), NULL)
#8 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#9 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#10 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#11 [internal function]: React\Promise\Deferred->resolve(NULL)
#12 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, NULL)
#13 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#14 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#15 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#16 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#17 [internal function]: React\Promise\Deferred->resolve(NULL)
#18 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, NULL)
#19 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(74): React\Promise\FulfilledPromise->then(Array, Array)
#20 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#21 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#22 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#23 [internal function]: React\Promise\Deferred->resolve(NULL)
#24 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, NULL)
#25 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#26 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#27 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#28 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#29 [internal function]: React\Promise\Deferred->resolve(true)
#30 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, true)
#31 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#32 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#33 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#34 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#35 [internal function]: React\Promise\Deferred->resolve(Object(Symfony\Component\Process\Process))
#36 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php(20): call_user_func(Array, Object(Symfony\Component\Process\Process))
#37 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(76): React\Promise\FulfilledPromise->then(Array, Array, Array)
#38 [internal function]: React\Promise\Deferred->React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#39 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(166): call_user_func(Object(Closure), Object(React\Promise\FulfilledPromise))
#40 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Deferred.php(95): React\Promise\Deferred->processQueue(Array, Object(React\Promise\FulfilledPromise))
#41 phar:///usr/local/bin/composer/vendor/react/promise/src/React/Promise/Promise.php(42): React\Promise\Deferred->resolve(Object(Symfony\Component\Process\Process))
#42 [internal function]: React\Promise\Promise->React\Promise\{closure}(Object(Symfony\Component\Process\Process))
#43 phar:///usr/local/bin/composer/src/Composer/Util/ProcessExecutor.php(316): call_user_func(Object(Closure), Object(Symfony\Component\Process\Process))
#44 phar:///usr/local/bin/composer/src/Composer/Util/Loop.php(92): Composer\Util\ProcessExecutor->countActiveJobs()
#45 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(462): Composer\Util\Loop->wait(Array, NULL)
#46 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(440): Composer\Installer\InstallationManager->waitOnPromises(Array)
#47 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(367): Composer\Installer\InstallationManager->executeBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array)
#48 phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php(266): Composer\Installer\InstallationManager->downloadAndExecuteBatch(Object(Composer\Repository\InstalledFilesystemRepository), Array, Array, true, true, Array)
#49 phar:///usr/local/bin/composer/src/Composer/Installer.php(706): Composer\Installer\InstallationManager->execute(Object(Composer\Repository\InstalledFilesystemRepository), Array, true, true)
#50 phar:///usr/local/bin/composer/src/Composer/Installer.php(543): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), true)
#51 phar:///usr/local/bin/composer/src/Composer/Installer.php(247): Composer\Installer->doUpdate(Object(Composer\Repository\InstalledFilesystemRepository), true)
#52 phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php(241): Composer\Installer->run()
#53 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#54 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#55 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\UpdateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#56 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(314): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#57 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(117): Composer\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#58 phar:///usr/local/bin/composer/src/Composer/Console/Application.php(125): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#59 phar:///usr/local/bin/composer/bin/composer(67): Composer\Console\Application->run()
#60 /usr/local/bin/composer(24): require('phar:///usr/loc...')
#61 {main}
  thrown in phar:///var/www/html/vendor/composer-unused/composer-unused-plugin/composer-unused.phar/config/container.php on line 10
```

**Comment by mdjdev** [comment]
I have the same issue. Have there been any updates or potential solutions to address it?

**Comment by icanhazstring** [comment]
Closed - as maintenance of composer-unused-plugin was discontinued
