### ISSUE TITLE
PHP Fatal error on running projects with local composer packages ("type": "path")

### ISSUE THREAD

**Issue by lptn** [composer-unused/composer-unused#515]
## Describe the bug

PHP exception on running `composer-unused`:
```
PHP Fatal error:  Uncaught TypeError: strrpos(): Argument #1 ($haystack) must be of type string, null given
```

Package version: v0.8.8

PHP Version => 8.2.5

## Additional information

```
Warning: Trying to access array offset on value of type null in phar:///some-path/composer-unused.phar/src/Composer/LocalRepositoryFactory.php on line 45
PHP Fatal error:  Uncaught TypeError: strrpos(): Argument #1 ($haystack) must be of type string, null given in phar:///some-path/composer-unused.phar/src/Composer/LocalRepositoryFactory.php:47
Stack trace:
#0 phar:///some-path/composer-unused.phar/src/Composer/LocalRepositoryFactory.php(47): strrpos(NULL, '.')
#1 phar:///some-path/composer-unused.phar/src/Composer/LocalRepositoryFactory.php(25): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\LocalRepositoryFactory->parseSourceUrlsFromInstalledJson('/Users/alies/co...')
#2 phar:///some-path/composer-unused.phar/src/Console/Command/UnusedCommand.php(79): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\LocalRepositoryFactory->create(Object(__ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Config))
#3 phar:///some-path/composer-unused.phar/vendor/symfony/console/Command/Command.php(259): __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute(Object(__ComposerUnused__\Symfony\Component\Console\Input\ArgvInput), Object(__ComposerUnused__\Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///some-path/composer-unused.phar/vendor/symfony/console/Application.php(870): __ComposerUnused__\Symfony\Component\Console\Command\Command->run(Object(__ComposerUnused__\Symfony\Component\Console\Input\ArgvInput), Object(__ComposerUnused__\Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///some-path/composer-unused.phar/vendor/symfony/console/Application.php(261): __ComposerUnused__\Symfony\Component\Console\Application->doRunCommand(Object(__ComposerUnused__\ComposerUnused\ComposerUnused\Console\Command\UnusedCommand), Object(__ComposerUnused__\Symfony\Component\Console\Input\ArgvInput), Object(__ComposerUnused__\Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///some-path/composer-unused.phar/vendor/symfony/console/Application.php(157): __ComposerUnused__\Symfony\Component\Console\Application->doRun(Object(__ComposerUnused__\Symfony\Component\Console\Input\ArgvInput), Object(__ComposerUnused__\Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///some-path/composer-unused.phar/bin/composer-unused(30): __ComposerUnused__\Symfony\Component\Console\Application->run(Object(__ComposerUnused__\Symfony\Component\Console\Input\ArgvInput))

```

____

The problem is here:
```php
     foreach ($installedJson['packages'] as $package) {
            $packageUrl = $package['source']['url'];
            /** @var int $lastDotPosition */
            $lastDotPosition = \strrpos($packageUrl, '.');
```

This is because if you use locally hosted packages, the json will be like:
```json
"dist": {
    "type": "path",
    "url": "packages/your-local-package",
    "reference": "532bdc46725a953ef5f4fb08e8699b3604e6f066"
},
```

This is how such package looks like in composer.json:
```json
       "repositories": [
       {
            "type": "path",
            "url": "packages/your-local-package",
        },
```

**Comment by icanhazstring** [comment]
Good catch. Thanks for the report.

**Comment by jlherren** [comment]
FWIW, this also happens with setasign.com's repository, which in my case looks like this:

```
    "repositories": {
        "setasign.com": {
            "type": "composer",
            "url": "https://www.setasign.com/downloads/"
        }
    }
```

**Comment by netpok** [comment]
I found this problem too, for locally it can be mitigated by adding a source definition to the packages `composer.json`.

**Comment by MarcinGladkowski** [comment]
MR https://github.com/composer-unused/composer-unused/pull/520

**Comment by icanhazstring** [comment]
Closed with #520

**Comment by AndreasA** [comment]
@icanhazstring Hi, any news regarding a release for this issue?

**Comment by icanhazstring** [comment]
Incoming soonish 🙂
Probably starting next week.
