### ISSUE TITLE
PHP Warning:  Undefined array key "packages"

### ISSUE THREAD

**Issue by carlos-landeira** [composer-unused/composer-unused#534]
I installed `composer-unused` via `phive` in my `src` project folder which contains `composer.json`. I tried running `php composer-unused.phar` but I'm getting this error:

```
PHP Warning:  Undefined array key "packages" in phar:///myApp/composer-unused.phar/src/Composer/LocalRepositoryFactory.php on line 42
PHP Fatal error:  Uncaught TypeError: array_reduce(): Argument #1 ($array) must be of type array, null given in phar://myApp/composer-unused.phar/src/Composer/LocalRepositoryFactory.php:45
Stack trace:
#0 phar:///myApp/composer-unused.phar/src/Composer/LocalRepositoryFactory.php(45): array_reduce()
#1 phar:///myApp/composer-unused.phar/src/Composer/LocalRepositoryFactory.php(26): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\LocalRepositoryFactory->parseSourceUrlsFromInstalledJson()
#2 phar:///myApp/composer-unused.phar/src/Console/Command/UnusedCommand.php(80): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\LocalRepositoryFactory->create()
#3 phar:///myApp/composer-unused.phar/vendor/symfony/console/Command/Command.php(259): __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute()
#4 phar:///myApp/composer-unused.phar/vendor/symfony/console/Application.php(870): __ComposerUnused__\Symfony\Component\Console\Command\Command->run()
#5 phar:///myApp/composer-unused.phar/vendor/symfony/console/Application.php(261): __ComposerUnused__\Symfony\Component\Console\Application->doRunCommand()
#6 phar:///myApp/composer-unused.phar/vendor/symfony/console/Application.php(157): __ComposerUnused__\Symfony\Component\Console\Application->doRun()
#7 phar:///myApp/composer-unused.phar/bin/composer-unused(30): __ComposerUnused__\Symfony\Component\Console\Application->run()
#8 phar:///myApp/composer-unused.phar/bin/composer-unused(31): __ComposerUnused__\{closure}()
#9 /myApp/composer-unused.phar(14): require('...')
#10 {main}
  thrown in phar:///myApp/composer-unused.phar/src/Composer/LocalRepositoryFactory.php on line 45
```

I removed all packages from `composer.json`, runned `composer update` then put the packages back in and runned `composer update` again but it still didn't fix it.

I checked the code, error seems to happen here:

```
$urls = \array_reduce($installedJson['packages'], static function ($agg, $package) use($packageUrlExtractor) {
            $agg[$package['name']] = ['url' => $packageUrlExtractor->getUrl($package)];
            return $agg;
        }, []);
```

Package version: 0.8.9

PHP version: 8.1.18

**Comment by icanhazstring** [comment]
Hi. Can you give more information about the packages you installed?

Because it seems to be that the installed.json seems to have a different format than we expected.

**Comment by carlos-landeira** [comment]
Sure, there's also one thing I didn't mention previously, I'm using Composer 1.10.26. Here is all the packages I'm using, I can't provide the entire `composer.json` file due to company policies.

```
"require": {
    "php": ">=5.6.0",
    "yiisoft/yii2": "2.0.47",
    "yiisoft/yii2-bootstrap": "2.0.*",
    "yiisoft/yii2-swiftmailer": "2.0.*",
    "yiisoft/yii2-bootstrap4": "~2.0.6",
    "almasaeed2010/adminlte": "2.3.11",
    "dmstr/yii2-adminlte-asset": "2.3.4",
    "kartik-v/yii2-datecontrol": "1.9.9",
    "kartik-v/yii2-widget-select2": "2.2.4",
    "kartik-v/yii2-widgets": "3.4.1",
    "kartik-v/yii2-money": "1.2.3",
    "kartik-v/yii2-mpdf": "1.0.6",
    "kartik-v/yii2-grid": "3.5.0",
    "kartik-v/yii2-helpers": "1.3.9",
    "kartik-v/yii2-popover-x": "1.3.5",
    "kartik-v/yii2-editable": "1.8.0",
    "kartik-v/yii2-widget-activeform": "1.6.2",
    "pelago/emogrifier": "7.0.0",
    "neverbounce/neverbounce-php": "3.0.*",
    "guzzlehttp/guzzle": "6.5.5",
    "phpoffice/phpspreadsheet": "^1.28",
    "fedemotta/yii2-aws-sdk": "2.*",
    "spatie/image-optimizer": "1.6.4",
    "firebase/php-jwt": "^5.0",
    "lcobucci/jwt": "^5.0",
    "scssphp/scssphp": "^1.4",
    "npm-asset/bootbox": "~5.4.0-stable",
    "npm-asset/moment": "~2.27.0-stable",
    "npm-asset/fullcalendar": "5.2.0",
    "npm-asset/dropzone": "~5.7.0-stable",
    "npm-asset/highcharts": "~8.1.2-stable",
    "bower-asset/bootstrap-tagsinput": "0.8.*",
    "bower-asset/bootstrap-treeview": "1.2.*",
    "bower-asset/bootstrap3-typeahead": "4.0.*",
    "chillerlan/php-qrcode": "^2.0",
    "ext-json": "*",
    "ethercreative/yii2-ip-ratelimiter":"1.*",
    "spatie/pdf-to-image": "2.2.0"
  },
  "require-dev": {
    "yiisoft/yii2-codeception": "*",
    "yiisoft/yii2-debug": "*",
    "yiisoft/yii2-gii": "*",
    "yiisoft/yii2-faker": "*"
  },
```

Correct me if that's not the information you were looking for.

**Comment by icanhazstring** [comment]
Thanks. That might help figuring out the issue.

**Comment by MarcinGladkowski** [comment]
@icanhazstring @carlos-landeira 
I tested installing packages from the same `composer.json` using Composer v1 and Composer v2. 

Result for `vendor/composer/installed.json`

Composer version 1.10.26
`json
[
    {
        "name": "zendframework/zendframework",
        "version": "2.4.13",
        "version_normalized": "2.4.13.0",
 // ...
`

**Composer version 2.2.8**
`json
{
    "packages": [
        {
            "name": "zendframework/zendframework",
            "version": "2.4.13",
            "version_normalized": "2.4.13.0",

`

**Comment by icanhazstring** [comment]
Composer V1 Support ended over 2 years already. So I won't add support here.

The only thing we could do is print a warning and probably skip the execution that V1 is not supported.

**Comment by carlos-landeira** [comment]
Understandable, thanks for your support.
