### ISSUE TITLE
 Undefined array key "composer/composer"

### ISSUE THREAD

**Issue by JanWennrichPCSG** [composer-unused/composer-unused#559]
## Describe the bug

I tried running `composer-unused` on my project via the PHAR and as a locally installed dev dependency.  
In both cases I get the error/warning ' Undefined array key "composer/composer"'

## Additional information

The error occurred with PHP `7.4`, `8.0` and `8.1`.
<details>
  <summary>Entire warning with stacktrace</summary>

```
❯ php8.1 composer-unused.phar
 0/2 [>---------------------------]   0%PHP Warning:  Undefined array key "composer/composer" in phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Composer/PackageFactory.php on line 13
PHP Stack trace:
PHP   1. {main}() /home/jan/PhpStormProjects/package-countries/composer-unused.phar:0
PHP   2. require() /home/jan/PhpStormProjects/package-countries/composer-unused.phar:14
PHP   3. __ComposerUnused__\{closure:phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/bin/composer-unused:11-31}($argv = [0 => 'composer-unused.phar']) phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/bin/composer-unused:31
PHP   4. __ComposerUnused__\Symfony\Component\Console\Application->run($input = class __ComposerUnused__\Symfony\Component\Console\Input\ArgvInput { protected $definition = class __ComposerUnused__\Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $lastArrayArgument = NULL; private $lastOptionalArgument = class __ComposerUnused__\Symfony\Component\Console\Input\InputArgument { ... }; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = []; protected $interactive = TRUE; private $tokens = []; private $parsed = [] }, $output = *uninitialized*) phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/bin/composer-unused:30
PHP   5. __ComposerUnused__\Symfony\Component\Console\Application->doRun($input = class __ComposerUnused__\Symfony\Component\Console\Input\ArgvInput { protected $definition = class __ComposerUnused__\Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $lastArrayArgument = NULL; private $lastOptionalArgument = class __ComposerUnused__\Symfony\Component\Console\Input\InputArgument { ... }; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = []; protected $interactive = TRUE; private $tokens = []; private $parsed = [] }, $output = class __ComposerUnused__\Symfony\Component\Console\Output\ConsoleOutput { private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}verbosity = 32; private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}formatter = class __ComposerUnused__\Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class __ComposerUnused__\Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } }; private ${__ComposerUnused__\Symfony\Component\Console\Output\StreamOutput}stream = resource(2) of type (stream); private $stderr = class __ComposerUnused__\Symfony\Component\Console\Output\StreamOutput { private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}verbosity = 32; private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}formatter = class __ComposerUnused__\Symfony\Component\Console\Formatter\OutputFormatter { ... }; private $stream = resource(3) of type (stream) }; private $consoleSectionOutputs = [] }) phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/vendor/symfony/console/Application.php:157
PHP   6. __ComposerUnused__\Symfony\Component\Console\Application->doRunCommand($command = class __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Command\UnusedCommand { private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}application = class __ComposerUnused__\Symfony\Component\Console\Application { private $commands = [...]; private $wantHelps = FALSE; private $runningCommand = ...; private $name = 'composer-unused'; private $version = '0.8.7'; private $commandLoader = NULL; private $catchExceptions = TRUE; private $autoExit = TRUE; private $definition = class __ComposerUnused__\Symfony\Component\Console\Input\InputDefinition { ... }; private $helperSet = class __ComposerUnused__\Symfony\Component\Console\Helper\HelperSet { ... }; private $dispatcher = NULL; private $terminal = class __ComposerUnused__\Symfony\Component\Console\Terminal { ... }; private $defaultCommand = 'unused'; private $singleCommand = FALSE; private $initialized = TRUE; private $signalRegistry = class __ComposerUnused__\Symfony\Component\Console\SignalRegistry\SignalRegistry { ... }; private $signalsToDispatchEvent = [...] }; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}name = 'unused'; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}processTitle = NULL; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}aliases = []; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}definition = class __ComposerUnused__\Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $lastArrayArgument = NULL; private $lastOptionalArgument = class __ComposerUnused__\Symfony\Component\Console\Input\InputArgument { ... }; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}hidden = FALSE; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}help = ''; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}description = 'Show unused packages by scanning and comparing package namespaces against your source.'; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}fullDefinition = class __ComposerUnused__\Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $lastArrayArgument = NULL; private $lastOptionalArgument = class __ComposerUnused__\Symfony\Component\Console\Input\InputArgument { ... }; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}ignoreValidationErrors = FALSE; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}code = NULL; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}synopsis = []; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}usages = []; private ${__ComposerUnused__\Symfony\Component\Console\Command\Command}helperSet = class __ComposerUnused__\Symfony\Component\Console\Helper\HelperSet { private $helpers = [...]; private $command = NULL }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Command\Handler\CollectConsumedSymbolsCommandHandler $collectConsumedSymbolsCommandHandler = class __ComposerUnused__\ComposerUnused\ComposerUnused\Command\Handler\CollectConsumedSymbolsCommandHandler { private __ComposerUnused__\ComposerUnused\ComposerUnused\Symbol\ConsumedSymbolLoaderBuilder $consumedSymbolLoaderBuilder = class __ComposerUnused__\ComposerUnused\ComposerUnused\Symbol\ConsumedSymbolLoaderBuilder { ... } }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Command\Handler\CollectRequiredDependenciesCommandHandler $collectRequiredDependenciesCommandHandler = class __ComposerUnused__\ComposerUnused\ComposerUnused\Command\Handler\CollectRequiredDependenciesCommandHandler { private __ComposerUnused__\ComposerUnused\ComposerUnused\PackageResolver $packageResolver = class __ComposerUnused__\ComposerUnused\ComposerUnused\PackageResolver { ... }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Symbol\ProvidedSymbolLoaderBuilder $providedSymbolLoaderBuilder = class __ComposerUnused__\ComposerUnused\ComposerUnused\Symbol\ProvidedSymbolLoaderBuilder { ... } }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\ConfigFactory $configFactory = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\ConfigFactory { private __ComposerUnused__\Symfony\Component\Serializer\SerializerInterface $serializer = class __ComposerUnused__\Symfony\Component\Serializer\Serializer { ... } }; private __ComposerUnused__\ComposerUnused\ComposerUnused\OutputFormatter\FormatterFactory $formatterFactory = class __ComposerUnused__\ComposerUnused\ComposerUnused\OutputFormatter\FormatterFactory { private __ComposerUnused__\OndraM\CiDetector\CiDetectorInterface $ciDetector = class __ComposerUnused__\OndraM\CiDetector\CiDetector { ... } }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\LocalRepositoryFactory $localRepositoryFactory = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\LocalRepositoryFactory { private __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory $packageFactory = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory { ... }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\ConfigFactory $configFactory = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\ConfigFactory { ... }; private __ComposerUnused__\Symfony\Component\Serializer\Serializer $serializer = class __ComposerUnused__\Symfony\Component\Serializer\Serializer { ... } }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory $packageFactory = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory {  }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Configuration\ConfigurationProvider $configurationProvider = class __ComposerUnused__\ComposerUnused\ComposerUnused\Configuration\ConfigurationProvider {  } }, $input = class __ComposerUnused__\Symfony\Component\Console\Input\ArgvInput { protected $definition = class __ComposerUnused__\Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $lastArrayArgument = NULL; private $lastOptionalArgument = class __ComposerUnused__\Symfony\Component\Console\Input\InputArgument { ... }; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = []; protected $interactive = TRUE; private $tokens = []; private $parsed = [] }, $output = class __ComposerUnused__\Symfony\Component\Console\Output\ConsoleOutput { private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}verbosity = 32; private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}formatter = class __ComposerUnused__\Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class __ComposerUnused__\Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } }; private ${__ComposerUnused__\Symfony\Component\Console\Output\StreamOutput}stream = resource(2) of type (stream); private $stderr = class __ComposerUnused__\Symfony\Component\Console\Output\StreamOutput { private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}verbosity = 32; private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}formatter = class __ComposerUnused__\Symfony\Component\Console\Formatter\OutputFormatter { ... }; private $stream = resource(3) of type (stream) }; private $consoleSectionOutputs = [] }) phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/vendor/symfony/console/Application.php:261
PHP   7. __ComposerUnused__\Symfony\Component\Console\Command\Command->run($input = class __ComposerUnused__\Symfony\Component\Console\Input\ArgvInput { protected $definition = class __ComposerUnused__\Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $lastArrayArgument = NULL; private $lastOptionalArgument = class __ComposerUnused__\Symfony\Component\Console\Input\InputArgument { ... }; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = []; protected $interactive = TRUE; private $tokens = []; private $parsed = [] }, $output = class __ComposerUnused__\Symfony\Component\Console\Output\ConsoleOutput { private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}verbosity = 32; private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}formatter = class __ComposerUnused__\Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class __ComposerUnused__\Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } }; private ${__ComposerUnused__\Symfony\Component\Console\Output\StreamOutput}stream = resource(2) of type (stream); private $stderr = class __ComposerUnused__\Symfony\Component\Console\Output\StreamOutput { private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}verbosity = 32; private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}formatter = class __ComposerUnused__\Symfony\Component\Console\Formatter\OutputFormatter { ... }; private $stream = resource(3) of type (stream) }; private $consoleSectionOutputs = [] }) phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/vendor/symfony/console/Application.php:870
PHP   8. __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute($input = class __ComposerUnused__\Symfony\Component\Console\Input\ArgvInput { protected $definition = class __ComposerUnused__\Symfony\Component\Console\Input\InputDefinition { private $arguments = [...]; private $requiredCount = 0; private $lastArrayArgument = NULL; private $lastOptionalArgument = class __ComposerUnused__\Symfony\Component\Console\Input\InputArgument { ... }; private $options = [...]; private $negations = [...]; private $shortcuts = [...] }; protected $stream = NULL; protected $options = []; protected $arguments = []; protected $interactive = TRUE; private $tokens = []; private $parsed = [] }, $output = class __ComposerUnused__\Symfony\Component\Console\Output\ConsoleOutput { private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}verbosity = 32; private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}formatter = class __ComposerUnused__\Symfony\Component\Console\Formatter\OutputFormatter { private $decorated = TRUE; private $styles = [...]; private $styleStack = class __ComposerUnused__\Symfony\Component\Console\Formatter\OutputFormatterStyleStack { ... } }; private ${__ComposerUnused__\Symfony\Component\Console\Output\StreamOutput}stream = resource(2) of type (stream); private $stderr = class __ComposerUnused__\Symfony\Component\Console\Output\StreamOutput { private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}verbosity = 32; private ${__ComposerUnused__\Symfony\Component\Console\Output\Output}formatter = class __ComposerUnused__\Symfony\Component\Console\Formatter\OutputFormatter { ... }; private $stream = resource(3) of type (stream) }; private $consoleSectionOutputs = [] }) phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/vendor/symfony/console/Command/Command.php:259
PHP   9. __ComposerUnused__\ComposerUnused\ComposerUnused\Command\Handler\CollectRequiredDependenciesCommandHandler->collect($command = class __ComposerUnused__\ComposerUnused\ComposerUnused\Command\LoadRequiredDependenciesCommand { private string $baseDir = '/home/jan/PhpStormProjects/package-countries/vendor'; private array $packageLinks = [0 => class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Link { ... }, 1 => class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Link { ... }]; private __ComposerUnused__\ComposerUnused\Contracts\RepositoryInterface $packageRepository = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\LocalRepository { private __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\InstalledVersions $installedVersions = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\InstalledVersions { ... }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory $packageFactory = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory { ... }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\ConfigFactory $configFactory = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\ConfigFactory { ... } }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Configuration\Configuration $configuration = class __ComposerUnused__\ComposerUnused\ComposerUnused\Configuration\Configuration { private array $namedFilters = [...]; private array $patternFilters = [...]; private array $additionalFiles = [...]; private ?string $dependenciesDir = NULL }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Progress\ProgressBarInterface $progressBar = class __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Progress\DefaultProgressBarDecorator { private __ComposerUnused__\Symfony\Component\Console\Helper\ProgressBar $progressBar = class __ComposerUnused__\Symfony\Component\Console\Helper\ProgressBar { ... }; private bool $noProgress = FALSE } }) phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Console/Command/UnusedCommand.php:90
PHP  10. __ComposerUnused__\ComposerUnused\ComposerUnused\PackageResolver->resolve($packageLink = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Link { private string $target = 'quiqqer/quiqqer'; private int $line = 18 }, $repository = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\LocalRepository { private __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\InstalledVersions $installedVersions = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\InstalledVersions { private array $installed = [...] }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory $packageFactory = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory {  }; private __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\ConfigFactory $configFactory = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\ConfigFactory { private __ComposerUnused__\Symfony\Component\Serializer\SerializerInterface $serializer = class __ComposerUnused__\Symfony\Component\Serializer\Serializer { ... } } }) phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Command/Handler/CollectRequiredDependenciesCommandHandler.php:28
PHP  11. __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\LocalRepository->findPackage($name = 'quiqqer/quiqqer') phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/PackageResolver.php:19
PHP  12. __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory->fromConfig($config = class __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Config { protected array $config = []; protected string $name = 'quiqqer/quiqqer'; private array $require = ['php' => '>=7.4', 'composer/composer' => '1.9.*|2.*', 'tedivm/stash' => '0.17.*', 'phpmailer/phpmailer' => '~6.0', 'symfony/http-foundation' => '>=2.3|3.*|4.2.*', 'symfony/console' => '4.*|5.*|6.*', 'symfony/polyfill-php80' => '*', 'symfony/polyfill-php81' => '*', 'symfony/polyfill-php82' => '*', 'symfony/polyfill-php83' => '*', 'html2text/html2text' => '4.*', 'intervention/image' => '2.*', 't7systems/blowfish' => '1.0.0', 'dusank/knapsack' => '8.*|9.*|10.*', 'league/climate' => '3.*', 'ramsey/uuid' => '3.*', 'neitanod/forceutf8' => '*', 'league/csv' => '9.*', 'masterminds/html5' => '^2.0', 'oomphinc/composer-installers-extender' => '^2.0', 'monolog/monolog' => '2.*', 'quiqqer/composer' => '>=1.4.2|dev-master|dev-dev', 'quiqqer/controls' => '^1.1.1|dev-master|dev-dev', 'quiqqer/dashboard' => '1.*|dev-master|dev-dev', 'quiqqer/qui' => '>=1.5|dev-master|dev-dev', 'quiqqer/qui-php' => '>=0.12|dev-master|dev-dev', 'quiqqer/smarty3' => '1.*|dev-master|dev-dev', 'quiqqer/ckeditor4' => '2.*|1.*|dev-master|dev-dev', 'quiqqer/calendar-controls' => '1.*|dev-master|dev-dev', 'quiqqer/countries' => '1.*|dev-master|dev-dev', 'quiqqer/colorpicker' => '>=1.1|dev-master|dev-dev', 'quiqqer/translator' => '>=1.9|dev-master|dev-dev', 'quiqqer/utils' => '>=1.22|dev-master|dev-dev', 'quiqqer/cron' => '^1.10.2|dev-master|dev-dev', 'quiqqer/log' => '>=1.6|dev-master|dev-dev', 'quiqqer/login-logger' => '1.*|dev-master|dev-dev', 'quiqqer/diashow' => '>=0.9|dev-master|dev-dev', 'quiqqer/lockclient' => '1.*|dev-master|dev-dev', 'quiqqer/messages' => '1.*|dev-master|dev-dev', 'quiqqer/meta' => '^2.1.0|dev-master|dev-dev', 'quiqqer/fontawesome' => '>=4.8|dev-master|dev-dev', 'quiqqer/backendsearch' => '1.*|dev-master|dev-dev', 'quiqqer/requirements' => '3.*|dev-master|dev-dev', 'quiqqer/demodata' => '^1.0|dev-master|dev-dev', 'quiqqer-asset/animejs' => '*', 'quiqqer-asset/intl' => '1.*', 'quiqqer-asset/nouislider' => '>=15', 'quiqqer-asset/mustache' => '4.*', 'quiqqer-asset/urijs' => '1.*', 'quiqqer-asset/downloadjs' => '1.*', 'quiqqer-asset/requirejs' => '2.*', 'quiqqer-asset/navigo' => '*', 'quiqqer-asset/history-events' => '*', 'quiqqer-asset/ace-builds' => '*']; private array $autoload = ['psr-0' => [...], 'classmap' => [...]]; private array $suggest = []; private array $extra = []; private string $rawContent = '{\n    "name": "quiqqer\\/quiqqer",\n    "type": "quiqqer-system",\n    "description": "A modular based management system written in JavaScript and PHP",\n    "license": "GPL-3.0-or-later",\n    "authors": [\n        {\n            "name": "Henning Leutz",\n            "email": "leutz@pcsg.de",\n            "homepage": "http:\\/\\/www.pcsg.de",\n            "role": "Developer"\n        },\n        {\n            "name": "Moritz Scholz",\n            "email": "scholz@pcsg.de",\n            "homepage": "http:\\/\\/www.pcsg.de",\n'...; private string $baseDir = '/home/jan/PhpStormProjects/package-countries/vendor/composer/../quiqqer/quiqqer'; private ?string $url = 'https://update.quiqqer.com/files/quiqqer/quiqqer/quiqqer-1.8.2.zip' }) phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Composer/LocalRepository.php:38
PHP  13. array_map($callback = class Closure { virtual $closure = "__ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory::__ComposerUnused__\ComposerUnused\ComposerUnused\Composer\{closure}", public $static = ['requireLines' => [...]]; public $parameter = ['$name' => '<required>'] }, $array = [0 => 'php', 1 => 'composer/composer', 2 => 'tedivm/stash', 3 => 'phpmailer/phpmailer', 4 => 'symfony/http-foundation', 5 => 'symfony/console', 6 => 'symfony/polyfill-php80', 7 => 'symfony/polyfill-php81', 8 => 'symfony/polyfill-php82', 9 => 'symfony/polyfill-php83', 10 => 'html2text/html2text', 11 => 'intervention/image', 12 => 't7systems/blowfish', 13 => 'dusank/knapsack', 14 => 'league/climate', 15 => 'ramsey/uuid', 16 => 'neitanod/forceutf8', 17 => 'league/csv', 18 => 'masterminds/html5', 19 => 'oomphinc/composer-installers-extender', 20 => 'monolog/monolog', 21 => 'quiqqer/composer', 22 => 'quiqqer/controls', 23 => 'quiqqer/dashboard', 24 => 'quiqqer/qui', 25 => 'quiqqer/qui-php', 26 => 'quiqqer/smarty3', 27 => 'quiqqer/ckeditor4', 28 => 'quiqqer/calendar-controls', 29 => 'quiqqer/countries', 30 => 'quiqqer/colorpicker', 31 => 'quiqqer/translator', 32 => 'quiqqer/utils', 33 => 'quiqqer/cron', 34 => 'quiqqer/log', 35 => 'quiqqer/login-logger', 36 => 'quiqqer/diashow', 37 => 'quiqqer/lockclient', 38 => 'quiqqer/messages', 39 => 'quiqqer/meta', 40 => 'quiqqer/fontawesome', 41 => 'quiqqer/backendsearch', 42 => 'quiqqer/requirements', 43 => 'quiqqer/demodata', 44 => 'quiqqer-asset/animejs', 45 => 'quiqqer-asset/intl', 46 => 'quiqqer-asset/nouislider', 47 => 'quiqqer-asset/mustache', 48 => 'quiqqer-asset/urijs', 49 => 'quiqqer-asset/downloadjs', 50 => 'quiqqer-asset/requirejs', 51 => 'quiqqer-asset/navigo', 52 => 'quiqqer-asset/history-events', 53 => 'quiqqer-asset/ace-builds']) phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Composer/PackageFactory.php:14
PHP  14. __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory::__ComposerUnused__\ComposerUnused\ComposerUnused\Composer\{closure:phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Composer/PackageFactory.php:12-14}($name = 'composer/composer') phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Composer/PackageFactory.php:14
PHP Fatal error:  Uncaught TypeError: __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Link::__construct(): Argument #2 ($line) must be of type int, null given, called in phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Composer/PackageFactory.php on line 13 and defined in phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Composer/Link.php:11
Stack trace:
#0 phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Composer/PackageFactory.php(13): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\Link->__construct()
#1 [internal function]: __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory::__ComposerUnused__\ComposerUnused\ComposerUnused\Composer\{closure}()
#2 phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Composer/PackageFactory.php(14): array_map()
#3 phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Composer/LocalRepository.php(38): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\PackageFactory->fromConfig()
#4 phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/PackageResolver.php(19): __ComposerUnused__\ComposerUnused\ComposerUnused\Composer\LocalRepository->findPackage()
#5 phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Command/Handler/CollectRequiredDependenciesCommandHandler.php(28): __ComposerUnused__\ComposerUnused\ComposerUnused\PackageResolver->resolve()
#6 phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Console/Command/UnusedCommand.php(90): __ComposerUnused__\ComposerUnused\ComposerUnused\Command\Handler\CollectRequiredDependenciesCommandHandler->collect()
#7 phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/vendor/symfony/console/Command/Command.php(259): __ComposerUnused__\ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute()
#8 phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/vendor/symfony/console/Application.php(870): __ComposerUnused__\Symfony\Component\Console\Command\Command->run()
#9 phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/vendor/symfony/console/Application.php(261): __ComposerUnused__\Symfony\Component\Console\Application->doRunCommand()
#10 phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/vendor/symfony/console/Application.php(157): __ComposerUnused__\Symfony\Component\Console\Application->doRun()
#11 phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/bin/composer-unused(30): __ComposerUnused__\Symfony\Component\Console\Application->run()
#12 phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/bin/composer-unused(31): __ComposerUnused__\{closure}()
#13 /home/jan/PhpStormProjects/package-countries/composer-unused.phar(14): require('...')
#14 {main}
  thrown in phar:///home/jan/PhpStormProjects/package-countries/composer-unused.phar/src/Composer/Link.php on line 11
```

</details>

<details>
    <summary>composer.json</summary>

```json
{
    "name": "quiqqer\/countries",
    "type": "quiqqer-plugin",
    "description": "Extend QUIQQER with a country database",
    "license": "MIT",
    "authors": [
        {
            "name": "Henning Leutz",
            "email": "leutz@pcsg.de",
            "homepage": "http:\/\/www.pcsg.de",
            "role": "Developer"
        }
    ],
    "support": {
        "email": "support@pcsg.de"
    },
    "require": {
        "quiqqer/quiqqer": "*",
        "quiqqer/utils": "*@dev"
    },
    "require-dev": {
        "mockery/mockery": "^1.6",
        "phpunit/phpunit": "^10.3@dev"
    },
    "autoload": {
        "psr-0": {
            "QUI": "src\/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "QUI\\Countries\\": "tests/QUI/Countries"
        }
    },
    "repositories": {
        "qassets": {
            "type": "composer",
            "url": "https://assets.quiqqer.com"
        },
        "qcomposer": {
            "type": "composer",
            "url": "https://composer.quiqqer.com"
        },
        "qupdate": {
            "type": "composer",
            "url": "https://update.quiqqer.com"
        }
    },
    "minimum-stability": "dev",
    "config": {
        "allow-plugins": {
            "composer/installers": true,
            "pestphp/pest-plugin": true,
            "oomphinc/composer-installers-extender": true
        }
    }
}
```
</details>

**Comment by MarcinGladkowski** [comment]
Hi! 

@icanhazstring @JanWennrichPCSG 

The problem is with dependencies escaped with backslash e.g. `composer\/composer`
The **quiqqer/quiqqer** package and other components has dependencies required in that way.

Packages: `https://github.com/QUIQQER/QUIQQER/blob/master/composer.json`

Composer from version 2 requires dependencies saved only with pattern [name](https://getcomposer.org/doc/04-schema.md#name) `^[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9](([_.]|-{1,2})?[a-z0-9]+)*$`

> Note: Before Composer version 2.0, a name could contain any character, including white spaces.

We can parse it or not support that cases by skipping it.

**Comment by icanhazstring** [comment]
Yes. Sounds like a compatibility issue we should ignore 👍

**Comment by MarcinGladkowski** [comment]
@icanhazstring 

What do you think about this solution ? https://github.com/composer-unused/composer-unused/pull/561

**Comment by icanhazstring** [comment]
Nice one. Thanks 🙏
