### ISSUE TITLE
Crash when Root Composer.json has no name

### ISSUE THREAD

**Issue by Hanmac** [composer-unused/composer-unused#578]
## Describe the bug

Some Projects doesn't have a name themselves:

```
PHP Fatal error:  Uncaught Error: Typed property ComposerUnused\ComposerUnused\Composer\Config::$name must not be accessed before initialization in /var/www/vendor/icanhazstring/composer-unused/src/Composer/Config.php:26
Stack trace:
#0 /var/www/vendor/icanhazstring/composer-unused/src/Composer/PackageFactory.php(16): ComposerUnused\ComposerUnused\Composer\Config->getName()
#1 /var/www/vendor/icanhazstring/composer-unused/src/Console/Command/UnusedCommand.php(150): ComposerUnused\ComposerUnused\Composer\PackageFactory->fromConfig(Object(ComposerUnused\ComposerUnused\Composer\Config))
#2 /var/www/vendor/symfony/console/Command/Command.php(298): ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(ComposerUnused\ComposerUnused\Console\Command\UnusedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/vendor/icanhazstring/composer-unused/bin/composer-unused(48): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#7 /var/www/vendor/icanhazstring/composer-unused/bin/composer-unused(49): {closure}(Array)
#8 /var/www/vendor/bin/composer-unused(119): include('/var/www/suppli...')
#9 {main}
  thrown in /var/www/vendor/icanhazstring/composer-unused/src/Composer/Config.php on line 26
```

while composer does this:
```
#composer why symfony/form
__root__                                 dev-master requires  symfony/form (5.4.*)
```

imo unused could also use this as default value

**Comment by icanhazstring** [comment]
It was fixed recently with a better error message.

But you are right, we could silently fall back to __root__ as a name. But then your configuration also has to reference that name to add additional files to it.

But I can think about that. Thanks 👍

**Comment by icanhazstring** [comment]
Solved with #671
